version: '3'
services:
  app:
    image: node:20
    container_name: frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
    working_dir: /app
    tty: true
    # command: npm install && npm run dev
