version: "3"
services:
  frontend:
    # Avec un image node depuis le docker hub
    # image: node:20
    # Depuis le Dockerfile dans le dossier front
    build:
      context: ./front
    container_name: front
    ports:
      - 5173:5173
    volumes:
      - ./front:/app
    working_dir: /app
    tty: true
    command: npm run dev
